/// 011-asci_nutsvars.do  NUTS Germany
/// - some nuts2 and nuts3 codes were changed in during our period (2004-2013) following reorganisations of admin areas  
/// - this do file changes nuts2 and nuts3 codes where possible to 2013-standards (in some cases unprecise, where former n2-areas were split to several new areas
/// Additionally, nuts3 codes imported from raw\Bruttolohn_nach_Kreisen.xls 
/// - generate factor variables (which can be labelled) from NUTS2 and NUTS3 string variables 
// this do file is called by 010-asci_fadn.do

// CHANGE NUTS2 AND NUTS3 CODES FROM YEARS BEFORE THE 2007 AND 2010 REORGANISATIONS OF ADMIN AREAS 

replace NUTS2 = "DE40" if inlist(NUTS2,"DE41","DE42" ) // BBG Nordost (DE41) and Südwest (DE42) were merged from 2010 on  (2006-2010.xls)
* Brandenburg
replace NUTS3 = "DE403" if NUTS3 == "DE411" // following merge of DE41 and DE42 from 2010 on (2006-2010.xls)
replace NUTS3 = "DE405" if NUTS3 == "DE412" // following merge of DE41 and DE42 from 2010 on (2006-2010.xls)
replace NUTS3 = "DE409" if NUTS3 == "DE413" // following merge of DE41 and DE42 from 2010 on (2006-2010.xls)
replace NUTS3 = "DE40A" if NUTS3 == "DE414" // following merge of DE41 and DE42 from 2010 on (2006-2010.xls)
replace NUTS3 = "DE40C" if NUTS3 == "DE415" // following merge of DE41 and DE42 from 2010 on (2006-2010.xls)
replace NUTS3 = "DE40D" if NUTS3 == "DE416" // following merge of DE41 and DE42 from 2010 on (2006-2010.xls)
replace NUTS3 = "DE40F" if NUTS3 == "DE417" // following merge of DE41 and DE42 from 2010 on (2006-2010.xls)
replace NUTS3 = "DE40I" if NUTS3 == "DE418" // following merge of DE41 and DE42 from 2010 on (2006-2010.xls)
replace NUTS3 = "DE401" if NUTS3 == "DE421" // following merge of DE41 and DE42 from 2010 on (2006-2010.xls)
replace NUTS3 = "DE402" if NUTS3 == "DE422" // following merge of DE41 and DE42 from 2010 on (2006-2010.xls)
replace NUTS3 = "DE404" if NUTS3 == "DE423" // following merge of DE41 and DE42 from 2010 on (2006-2010.xls)
replace NUTS3 = "DE406" if NUTS3 == "DE424" // following merge of DE41 and DE42 from 2010 on (2006-2010.xls)
replace NUTS3 = "DE407" if NUTS3 == "DE425" // following merge of DE41 and DE42 from 2010 on (2006-2010.xls)
replace NUTS3 = "DE408" if NUTS3 == "DE426" // following merge of DE41 and DE42 from 2010 on (2006-2010.xls)
replace NUTS3 = "DE40B" if NUTS3 == "DE427" // following merge of DE41 and DE42 from 2010 on (2006-2010.xls)
replace NUTS3 = "DE40E" if NUTS3 == "DE428" // following merge of DE41 and DE42 from 2010 on (2006-2010.xls)
replace NUTS3 = "DE40G" if NUTS3 == "DE429" // following merge of DE41 and DE42 from 2010 on (2006-2010.xls)
replace NUTS3 = "DE40H" if NUTS3 == "DE42A" // following merge of DE41 and DE42 from 2010 on (2006-2010.xls)
* NRW
replace NUTS3 = "DEA2D" if inlist(NUTS3,"DEA21","DEA25") //   (2006-2010.xls)
replace NUTS3 = "DEA23" if inlist(NUTS3,"DEA20") //  DEA20 does not exist. I guess Köln
* Saxony
replace NUTS3 = "DED21" if NUTS3 =="DED3" //  nuts2 dresden
replace NUTS3 = "DED41" if NUTS3 =="DED1" //  nuts2 Chemniz
replace NUTS3 = "DED41" if NUTS3 =="DED11" //  Chemniz kreisfreie Stadt
replace NUTS3 = "DED42" if inlist(NUTS3,"DED14","DED18","DED1A","DED1B" ) //           (2006-2010.xls)
replace NUTS3 = "DED43" if inlist(NUTS3,"DED16","DED19","DED33") //                    (2006-2010.xls)
replace NUTS3 = "DED44" if inlist(NUTS3,"DED12","DED17") //                            (2006-2010.xls)
replace NUTS3 = "DED45" if inlist(NUTS3,"DED13","DED15","DED1C" ) //                   (2006-2010.xls)
replace NUTS3 = "DED2C" if inlist(NUTS3,"DED23","DED24","DED2B" ) //                   (2006-2010.xls)
replace NUTS3 = "DED2D" if inlist(NUTS3,"DED22","DED26","DED28") //                    (2006-2010.xls)
replace NUTS3 = "DED2E" if inlist(NUTS3,"DED25","DED27") //                            (2006-2010.xls)
replace NUTS3 = "DED2F" if inlist(NUTS3,"DED2A","DED29") //                            (2006-2010.xls)
replace NUTS3 = "DED51" if NUTS3 =="DED31" //                                          (2006-2010.xls)
replace NUTS3 = "DED52" if inlist(NUTS3,"DED34","DED35" ) //                           (2006-2010.xls)
replace NUTS3 = "DED53" if inlist(NUTS3,"DED32","DED36" ) //                           (2006-2010.xls)


replace NUTS2 = "DED4" if substr(NUTS3,1,4) == "DED4"  | NUTS3=="DED1" // chemnitz     (2006-2010.xls)
replace NUTS2 = "DED5" if substr(NUTS3,1,4) == "DED5"  | NUTS3=="DED3" | NUTS2=="DED3"    // Leipzig   (2006-2010.xls)  ?????

* Saxony-Anhalt
replace NUTS2 = "DEE0" if inlist(NUTS2,"DEE1","DEE2","DEE3") // admin reform 2007 Dessau-Rosslau 

replace NUTS3 = "DEE01" if inlist(NUTS3,"DEE11") // admin reform 2007 Dessau-Rosslau 
replace NUTS3 = "DEE02" if inlist(NUTS3,"DEE21") // admin reform 2007  Halle
replace NUTS3 = "DEE03" if inlist(NUTS3,"DEE31") // admin reform 2007 Magdeburg
replace NUTS3 = "DEE04" if inlist(NUTS3,"DEE3B") // admin reform 2007 Altmarkkreis
replace NUTS3 = "DEE05" if inlist(NUTS3,"DEE14","DEE15") // admin reform 2007  Anhalt Bitterfeld
replace NUTS3 = "DEE06" if inlist(NUTS3,"DEE35") // admin reform 2007 Jerichoer L
replace NUTS3 = "DEE07" if inlist(NUTS3,"DEE33","DEE36") // admin reform 2007  Börde
replace NUTS3 = "DEE08" if inlist(NUTS3,"DEE22","DEE27") // admin reform 2007  Burgenland
replace NUTS3 = "DEE09" if inlist(NUTS3,"DEE34","DEE38","DEE3A") // admin reform 2007 Harz 
replace NUTS3 = "DEE0A" if inlist(NUTS3,"DEE23","DEE26") // admin reform 2007  Mansfeld Südharz
replace NUTS3 = "DEE0B" if inlist(NUTS3,"DEE24","DEE25") // admin reform 2007  Saalekreis
replace NUTS3 = "DEE0C" if inlist(NUTS3,"DEE13","DEE32","DEE39") // admin reform 2007 Salzlandkreis 
replace NUTS3 = "DEE0D" if inlist(NUTS3,"DEE37") // admin reform 2007 Stendal
replace NUTS3 = "DEE0E" if inlist(NUTS3,"DEE12","DEE16") // admin reform 2007  Wittenberg

*Mecklenburg Vorpommern  Gebietsreform zum 4.9.2011: reduce number of Landkreise (nuts3) from 12 to 6 (plus two kreisfreie Städte)
replace NUTS3 = "DE80J" if inlist(NUTS3,"DE80B","DE80C","DE808") // admin reform 2011 -> Mecklenburgische Seenplatte 
replace NUTS3 = "DE80K" if inlist(NUTS3,"DE807","DE809") // admin reform 2011 -> Landkr Rostock
replace NUTS3 = "DE80L" if inlist(NUTS3,"DE80D","DE80H") // admin reform 2011 -> Vorpommern-Rügen
replace NUTS3 = "DE80M" if inlist(NUTS3,"DE80E") // admin reform 2011 -> NW Mecklenburg
replace NUTS3 = "DE80N" if inlist(NUTS3,"DE801","DE80F","DE80I") // admin reform 2011 -> Vorpommern Greifswald
replace NUTS3 = "DE80O" if inlist(NUTS3,"DE80A","DE80G") // admin reform 2011 -> Ludwigslust-Parchim

replace NUTS3 = "DE80J" if inlist(NUTS3,"DE80") // admin reform 2011 nuts3 is missing so i use Mecklenburgische Seenplatte for this Kreis in MV

* Lower Saxony
replace NUTS3 = "DE91C" if inlist(NUTS3,"DE915","DE919") // admin reform 2016 -> Landkreis Göttingen

* Rheinland-Pfalz   reform of 1.7.2014 
replace NUTS3 = "DEB1C" if inlist(NUTS3,"DEB16") // admin reform 2014 -> boundary shift, so it is unprecise to consider the areas to be equal
replace NUTS3 = "DEB1D" if inlist(NUTS3,"DEB19") // admin reform 2014 -> boundary shift, so it is unprecise to consider the areas to be equal



* NUTS 2 Codes
gen     n2 = "DE11 Stuttgart"              if NUTS2== "DE11"
replace n2 = "DE12 Karlsruhe"              if NUTS2== "DE12"
replace n2 = "DE13 Freiburg"               if NUTS2== "DE13"
replace n2 = "DE14 Tübingen"               if NUTS2== "DE14"
replace n2 = "DE21 Oberbayern"             if NUTS2== "DE21"
replace n2 = "DE22 Niederbayern"           if NUTS2== "DE22"
replace n2 = "DE23 Oberpfalz"              if NUTS2== "DE23"
replace n2 = "DE24 Oberfranken"            if NUTS2== "DE24"
replace n2 = "DE25 Mittelfranken"          if NUTS2== "DE25"
replace n2 = "DE26 Unterfranken"           if NUTS2== "DE26"
replace n2 = "DE27 Schwaben"               if NUTS2== "DE27"
replace n2 = "DE30 Berlin"                 if NUTS2== "DE30"
replace n2 = "DE40 Brandenburg"            if NUTS2== "DE40"
replace n2 = "DE41 BBg-NO(<2010)"          if NUTS2== "DE41"
replace n2 = "DE42 BBg-SW(<2010)"          if NUTS2== "DE42"
replace n2 = "DE50 Bremen"                 if NUTS2== "DE50"
replace n2 = "DE60 Hamburg"                if NUTS2== "DE60"
replace n2 = "DE71 Darmstadt"              if NUTS2== "DE71"
replace n2 = "DE72 Gießen"                 if NUTS2== "DE72"
replace n2 = "DE73 Kassel"                 if NUTS2== "DE73"
replace n2 = "DE80 Mecklenburg-Vorpommern" if NUTS2== "DE80"
replace n2 = "DE91 Braunschweig"           if NUTS2== "DE91"
replace n2 = "DE92 Hannover"               if NUTS2== "DE92"
replace n2 = "DE93 Lüneburg"               if NUTS2== "DE93"
replace n2 = "DE94 Weser-Ems"              if NUTS2== "DE94"
replace n2 = "DEA1 Düsseldorf"             if NUTS2== "DEA1"
replace n2 = "DEA2 Köln"                   if NUTS2== "DEA2"
replace n2 = "DEA3 Münster"                if NUTS2== "DEA3"
replace n2 = "DEA4 Detmold"                if NUTS2== "DEA4"
replace n2 = "DEA5 Arnsberg"               if NUTS2== "DEA5"
replace n2 = "DEB1 Koblenz"                if NUTS2== "DEB1"
replace n2 = "DEB2 Trier"                  if NUTS2== "DEB2"
replace n2 = "DEB3 Rheinhessen-Pfalz"      if NUTS2== "DEB3"
replace n2 = "DEC0 Saarland"               if NUTS2== "DEC0"
replace n2 = "DED1 Chemnitz (<2010)"       if NUTS2== "DED1"
replace n2 = "DED2 Dresden (<2010)"        if NUTS2== "DED2"
replace n2 = "DED3 Leipzig (<2010)"        if NUTS2== "DED3"  
replace n2 = "DED4 Chemnitz"               if NUTS2== "DED4"
replace n2 = "DED5 Leipzig"                if NUTS2== "DED5"  
replace n2 = "DEE0 Sachsen-Anhalt"         if NUTS2== "DEE0"
replace n2 = "DEE1 SA, Dessau (<2007)"     if NUTS2== "DEE1"
replace n2 = "DEE2 SA, Halle (<2007)"      if NUTS2== "DEE2"
replace n2 = "DEE3 SA, Magdeb (<2007)"     if NUTS2== "DEE3"
replace n2 = "DEF0 Schleswig-Holstein"     if NUTS2== "DEF0"
replace n2 = "DEG0 Thüringen"              if NUTS2== "DEG0"


encode n2, generate(NUTS2fv)  // nuts2 as factor variable labelled with clear names
label save NUTS2fv using "fmt\NUTS2fv", replace  // to be called in asci_Format...do
drop n2

* NUTS 3 Codes (source: a combination of: https://ec.europa.eu/eurostat/documents/345175/629341/2006-2010.xls  ,
*        /NUTS 2010 - NUTS 2013.xls , and //NUTS2013-NUTS2016.xlsx,   found via https://ec.europa.eu/eurostat/web/nuts/history   

gen     n3 = "DE111 Stuttgart, Stadtkreis"                                          if NUTS3 == "DE111"
replace n3 = "DE112 Böblingen"                                                      if NUTS3 == "DE112"
replace n3 = "DE113 Esslingen"                                                      if NUTS3 == "DE113"
replace n3 = "DE114 Göppingen"                                                      if NUTS3 == "DE114"
replace n3 = "DE115 Ludwigsburg"                                                    if NUTS3 == "DE115"
replace n3 = "DE116 Rems-Murr-Kreis"                                                if NUTS3 == "DE116"
replace n3 = "DE117 Heilbronn, Stadtkreis"                                          if NUTS3 == "DE117"
replace n3 = "DE118 Heilbronn, Landkreis"                                           if NUTS3 == "DE118"
replace n3 = "DE119 Hohenlohekreis"                                                 if NUTS3 == "DE119"
replace n3 = "DE11A Schwäbisch Hall"                                                if NUTS3 == "DE11A"
replace n3 = "DE11B Main-Tauber-Kreis"                                              if NUTS3 == "DE11B"
replace n3 = "DE11C Heidenheim"                                                     if NUTS3 == "DE11C"
replace n3 = "DE11D Ostalbkreis"                                                    if NUTS3 == "DE11D"
replace n3 = "DE121 Baden-Baden, Stadtkreis"                                        if NUTS3 == "DE121"
replace n3 = "DE122 Karlsruhe, Stadtkreis"                                          if NUTS3 == "DE122"
replace n3 = "DE123 Karlsruhe, Landkreis"                                           if NUTS3 == "DE123"
replace n3 = "DE124 Rastatt"                                                        if NUTS3 == "DE124"
replace n3 = "DE125 Heidelberg, Stadtkreis"                                         if NUTS3 == "DE125"
replace n3 = "DE126 Mannheim, Stadtkreis"                                           if NUTS3 == "DE126"
replace n3 = "DE127 Neckar-Odenwald-Kreis"                                          if NUTS3 == "DE127"
replace n3 = "DE128 Rhein-Neckar-Kreis"                                             if NUTS3 == "DE128"
replace n3 = "DE129 Pforzheim, Stadtkreis"                                          if NUTS3 == "DE129"
replace n3 = "DE12A Calw"                                                           if NUTS3 == "DE12A"
replace n3 = "DE12B Enzkreis"                                                       if NUTS3 == "DE12B"
replace n3 = "DE12C Freudenstadt"                                                   if NUTS3 == "DE12C"
replace n3 = "DE131 Freiburg im Breisgau, Stadtkreis"                               if NUTS3 == "DE131"
replace n3 = "DE132 Breisgau-Hochschwarzwald"                                       if NUTS3 == "DE132"
replace n3 = "DE133 Emmendingen"                                                    if NUTS3 == "DE133"
replace n3 = "DE134 Ortenaukreis"                                                   if NUTS3 == "DE134"
replace n3 = "DE135 Rottweil"                                                       if NUTS3 == "DE135"
replace n3 = "DE136 Schwarzwald-Baar-Kreis"                                         if NUTS3 == "DE136"
replace n3 = "DE137 Tuttlingen"                                                     if NUTS3 == "DE137"
replace n3 = "DE138 Konstanz"                                                       if NUTS3 == "DE138"
replace n3 = "DE139 Lörrach"                                                        if NUTS3 == "DE139"
replace n3 = "DE13A Waldshut"                                                       if NUTS3 == "DE13A"
replace n3 = "DE141 Reutlingen"                                                     if NUTS3 == "DE141"
replace n3 = "DE142 Tübingen, Landkreis"                                            if NUTS3 == "DE142"
replace n3 = "DE143 Zollernalbkreis"                                                if NUTS3 == "DE143"
replace n3 = "DE144 Ulm, Stadtkreis"                                                if NUTS3 == "DE144"
replace n3 = "DE145 Alb-Donau-Kreis"                                                if NUTS3 == "DE145"
replace n3 = "DE146 Biberach"                                                       if NUTS3 == "DE146"
replace n3 = "DE147 Bodenseekreis"                                                  if NUTS3 == "DE147"
replace n3 = "DE148 Ravensburg"                                                     if NUTS3 == "DE148"
replace n3 = "DE149 Sigmaringen"                                                    if NUTS3 == "DE149"
replace n3 = "DE211 Ingolstadt, Kreisfreie Stadt"                                   if NUTS3 == "DE211"
replace n3 = "DE212 München, Kreisfreie Stadt"                                      if NUTS3 == "DE212"
replace n3 = "DE213 Rosenheim, Kreisfreie Stadt"                                    if NUTS3 == "DE213"
replace n3 = "DE214 Altötting"                                                      if NUTS3 == "DE214"
replace n3 = "DE215 Berchtesgadener Land"                                           if NUTS3 == "DE215"
replace n3 = "DE216 Bad Tölz-Wolfratshausen"                                        if NUTS3 == "DE216"
replace n3 = "DE217 Dachau"                                                         if NUTS3 == "DE217"
replace n3 = "DE218 Ebersberg"                                                      if NUTS3 == "DE218"
replace n3 = "DE219 Eichstätt"                                                      if NUTS3 == "DE219"
replace n3 = "DE21A Erding"                                                         if NUTS3 == "DE21A"
replace n3 = "DE21B Freising"                                                       if NUTS3 == "DE21B"
replace n3 = "DE21C Fürstenfeldbruck"                                               if NUTS3 == "DE21C"
replace n3 = "DE21D Garmisch-Partenkirchen"                                         if NUTS3 == "DE21D"
replace n3 = "DE21E Landsberg am Lech"                                              if NUTS3 == "DE21E"
replace n3 = "DE21F Miesbach"                                                       if NUTS3 == "DE21F"
replace n3 = "DE21G Mühldorf a. Inn"                                                if NUTS3 == "DE21G"
replace n3 = "DE21H München, Landkreis"                                             if NUTS3 == "DE21H"
replace n3 = "DE21I Neuburg-Schrobenhausen"                                         if NUTS3 == "DE21I"
replace n3 = "DE21J Pfaffenhofen a. d. Ilm"                                         if NUTS3 == "DE21J"
replace n3 = "DE21K Rosenheim, Landkreis"                                           if NUTS3 == "DE21K"
replace n3 = "DE21L Starnberg"                                                      if NUTS3 == "DE21L"
replace n3 = "DE21M Traunstein"                                                     if NUTS3 == "DE21M"
replace n3 = "DE21N Weilheim-Schongau"                                              if NUTS3 == "DE21N"
replace n3 = "DE221 Landshut, Kreisfreie Stadt"                                     if NUTS3 == "DE221"
replace n3 = "DE222 Passau, Kreisfreie Stadt"                                       if NUTS3 == "DE222"
replace n3 = "DE223 Straubing, Kreisfreie Stadt"                                    if NUTS3 == "DE223"
replace n3 = "DE224 Deggendorf"                                                     if NUTS3 == "DE224"
replace n3 = "DE225 Freyung-Grafenau"                                               if NUTS3 == "DE225"
replace n3 = "DE226 Kelheim"                                                        if NUTS3 == "DE226"
replace n3 = "DE227 Landshut, Landkreis"                                            if NUTS3 == "DE227"
replace n3 = "DE228 Passau, Landkreis"                                              if NUTS3 == "DE228"
replace n3 = "DE229 Regen"                                                          if NUTS3 == "DE229"
replace n3 = "DE22A Rottal-Inn"                                                     if NUTS3 == "DE22A"
replace n3 = "DE22B Straubing-Bogen"                                                if NUTS3 == "DE22B"
replace n3 = "DE22C Dingolfing-Landau"                                              if NUTS3 == "DE22C"
replace n3 = "DE231 Amberg, Kreisfreie Stadt"                                       if NUTS3 == "DE231"
replace n3 = "DE232 Regensburg, Kreisfreie Stadt"                                   if NUTS3 == "DE232"
replace n3 = "DE233 Weiden i. d. Opf, Kreisfreie Stadt"                             if NUTS3 == "DE233"
replace n3 = "DE234 Amberg-Sulzbach"                                                if NUTS3 == "DE234"
replace n3 = "DE235 Cham"                                                           if NUTS3 == "DE235"
replace n3 = "DE236 Neumarkt i. d. OPf."                                            if NUTS3 == "DE236"
replace n3 = "DE237 Neustadt a.d.Waldnaab"                                          if NUTS3 == "DE237"
replace n3 = "DE238 Regensburg, Landkreis"                                          if NUTS3 == "DE238"
replace n3 = "DE239 Schwandorf"                                                     if NUTS3 == "DE239"
replace n3 = "DE23A Tirschenreuth"                                                  if NUTS3 == "DE23A"
replace n3 = "DE241 Bamberg, Kreisfreie Stadt"                                      if NUTS3 == "DE241"
replace n3 = "DE242 Bayreuth, Kreisfreie Stadt"                                     if NUTS3 == "DE242"
replace n3 = "DE243 Coburg, Kreisfreie Stadt"                                       if NUTS3 == "DE243"
replace n3 = "DE244 Hof, Kreisfreie Stadt"                                          if NUTS3 == "DE244"
replace n3 = "DE245 Bamberg, Landkreis"                                             if NUTS3 == "DE245"
replace n3 = "DE246 Bayreuth, Landkreis"                                            if NUTS3 == "DE246"
replace n3 = "DE247 Coburg, Landkreis"                                              if NUTS3 == "DE247"
replace n3 = "DE248 Forchheim"                                                      if NUTS3 == "DE248"
replace n3 = "DE249 Hof, Landkreis"                                                 if NUTS3 == "DE249"
replace n3 = "DE24A Kronach"                                                        if NUTS3 == "DE24A"
replace n3 = "DE24B Kulmbach"                                                       if NUTS3 == "DE24B"
replace n3 = "DE24C Lichtenfels"                                                    if NUTS3 == "DE24C"
replace n3 = "DE24D Wunsiedel i. Fichtelgebirge"                                    if NUTS3 == "DE24D"
replace n3 = "DE251 Ansbach, Kreisfreie Stadt"                                      if NUTS3 == "DE251"
replace n3 = "DE252 Erlangen, Kreisfreie Stadt"                                     if NUTS3 == "DE252"
replace n3 = "DE253 Fürth, Kreisfreie Stadt"                                        if NUTS3 == "DE253"
replace n3 = "DE254 Nürnberg, Kreisfreie Stadt"                                     if NUTS3 == "DE254"
replace n3 = "DE255 Schwabach, Kreisfreie Stadt"                                    if NUTS3 == "DE255"
replace n3 = "DE256 Ansbach, Landkreis"                                             if NUTS3 == "DE256"
replace n3 = "DE257 Erlangen-Höchstadt"                                             if NUTS3 == "DE257"
replace n3 = "DE258 Fürth, Landkreis"                                               if NUTS3 == "DE258"
replace n3 = "DE259 Nürnberger Land"                                                if NUTS3 == "DE259"
replace n3 = "DE25A Neustadt a. d. Aisch-Bad Windsheim"                             if NUTS3 == "DE25A"
replace n3 = "DE25B Roth"                                                           if NUTS3 == "DE25B"
replace n3 = "DE25C Weißenburg-Gunzenhausen"                                        if NUTS3 == "DE25C"
replace n3 = "DE261 Aschaffenburg, Kreisfreie Stadt"                                if NUTS3 == "DE261"
replace n3 = "DE262 Schweinfurt, Kreisfreie Stadt"                                  if NUTS3 == "DE262"
replace n3 = "DE263 Würzburg, Kreisfreie Stadt"                                     if NUTS3 == "DE263"
replace n3 = "DE264 Aschaffenburg, Landkreis"                                       if NUTS3 == "DE264"
replace n3 = "DE265 Bad Kissingen"                                                  if NUTS3 == "DE265"
replace n3 = "DE266 Rhön-Grabfeld"                                                  if NUTS3 == "DE266"
replace n3 = "DE267 Haßberge"                                                       if NUTS3 == "DE267"
replace n3 = "DE268 Kitzingen"                                                      if NUTS3 == "DE268"
replace n3 = "DE269 Miltenberg"                                                     if NUTS3 == "DE269"
replace n3 = "DE26A Main-Spessart"                                                  if NUTS3 == "DE26A"
replace n3 = "DE26B Schweinfurt, Landkreis"                                         if NUTS3 == "DE26B"
replace n3 = "DE26C Würzburg, Landkreis"                                            if NUTS3 == "DE26C"
replace n3 = "DE271 Augsburg, Kreisfreie Stadt"                                     if NUTS3 == "DE271"
replace n3 = "DE272 Kaufbeuren, Kreisfreie Stadt"                                   if NUTS3 == "DE272"
replace n3 = "DE273 Kempten (Allgäu), Kreisfreie Stadt"                             if NUTS3 == "DE273"
replace n3 = "DE274 Memmingen, Kreisfreie Stadt"                                    if NUTS3 == "DE274"
replace n3 = "DE275 Aichach-Friedberg"                                              if NUTS3 == "DE275"
replace n3 = "DE276 Augsburg, Landkreis"                                            if NUTS3 == "DE276"
replace n3 = "DE277 Dillingen a.d. Donau"                                           if NUTS3 == "DE277"
replace n3 = "DE278 Günzburg"                                                       if NUTS3 == "DE278"
replace n3 = "DE279 Neu-Ulm"                                                        if NUTS3 == "DE279"
replace n3 = "DE27A Lindau Bodensee)"                                               if NUTS3 == "DE27A"
replace n3 = "DE27B Ostallgäu"                                                      if NUTS3 == "DE27B"
replace n3 = "DE27C Unterallgäu"                                                    if NUTS3 == "DE27C"
replace n3 = "DE27D Donau-Ries"                                                     if NUTS3 == "DE27D"
replace n3 = "DE27E Oberallgäu"                                                     if NUTS3 == "DE27E"
replace n3 = "DE300 Berlin"                                                         if NUTS3 == "DE300"
replace n3 = "DE401 Brandenburg an der Havel, Kreisfreie Stadt"                     if NUTS3 == "DE401"
replace n3 = "DE402 Cottbus, Kreisfreie Stadt"                                      if NUTS3 == "DE402"
replace n3 = "DE403 Frankfurt (Oder), Kreisfreie Stadt"                             if NUTS3 == "DE403"
replace n3 = "DE404 Potsdam, Kreisfreie Stadt"                                      if NUTS3 == "DE404"
replace n3 = "DE405 Barnim"                                                         if NUTS3 == "DE405"
replace n3 = "DE406 Dahme-Spreewald"                                                if NUTS3 == "DE406"
replace n3 = "DE407 Elbe-Elster"                                                    if NUTS3 == "DE407"
replace n3 = "DE408 Havelland"                                                      if NUTS3 == "DE408"
replace n3 = "DE409 Märkisch-Oderland"                                              if NUTS3 == "DE409"
replace n3 = "DE40A Oberhavel"                                                      if NUTS3 == "DE40A"
replace n3 = "DE40B Oberspreewald-Lausitz"                                          if NUTS3 == "DE40B"
replace n3 = "DE40C Oder-Spree"                                                     if NUTS3 == "DE40C"
replace n3 = "DE40D Ostprignitz-Ruppin"                                             if NUTS3 == "DE40D"
replace n3 = "DE40E Potsdam-Mittelmark"                                             if NUTS3 == "DE40E"
replace n3 = "DE40F Prignitz"                                                       if NUTS3 == "DE40F"
replace n3 = "DE40G Spree-Neiße"                                                    if NUTS3 == "DE40G"
replace n3 = "DE40H Teltow-Fläming"                                                 if NUTS3 == "DE40H"
replace n3 = "DE40I Uckermark"                                                      if NUTS3 == "DE40I"
replace n3 = "DE411 Frankfurt (Oder), Kreisfreie Stadt (<2010)" if NUTS3 == "DE411"
replace n3 = "DE412 Barnim (<2010)" if NUTS3 == "DE412"
replace n3 = "DE413 Märkisch-Oderland (<2010)" if NUTS3 == "DE413"
replace n3 = "DE414 Oberhavel (<2010)" if NUTS3 == "DE414"
replace n3 = "DE415 Oder-Spree (<2010)" if NUTS3 == "DE415"
replace n3 = "DE416 Ostprignitz-Ruppin (<2010)" if NUTS3 == "DE416"
replace n3 = "DE417 Prignitz (<2010)" if NUTS3 == "DE417"
replace n3 = "DE418 Uckermark (<2010)" if NUTS3 == "DE418"
replace n3 = "DE421 Brandenburg an der Havel, Kreisfreie Stadt (<2010)" if NUTS3 == "DE421"
replace n3 = "DE422 Cottbus, Kreisfreie Stadt (<2010)" if NUTS3 == "DE422"
replace n3 = "DE423 Potsdam, Kreisfreie Stadt (<2010)" if NUTS3 == "DE423"
replace n3 = "DE424 Dahme-Spreewald (<2010)" if NUTS3 == "DE424"
replace n3 = "DE425 Elbe-Elster (<2010)" if NUTS3 == "DE425"
replace n3 = "DE426 Havelland (<2010)" if NUTS3 == "DE426"
replace n3 = "DE427 Oberspreewald-Lausitz (<2010)" if NUTS3 == "DE427"
replace n3 = "DE428 Potsdam-Mittelmark (<2010)" if NUTS3 == "DE428"
replace n3 = "DE429 Spree-Neiße (<2010)" if NUTS3 == "DE429"
replace n3 = "DE42A Teltow-Fläming (<2010)" if NUTS3 == "DE42A"
replace n3 = "DE501 Bremen, Kreisfreie Stadt"                                       if NUTS3 == "DE501"
replace n3 = "DE502 Bremerhaven, Kreisfreie Stadt"                                  if NUTS3 == "DE502"
replace n3 = "DE600 Hamburg"                                                        if NUTS3 == "DE600"
replace n3 = "DE711 Darmstadt, Kreisfreie Stadt"                                    if NUTS3 == "DE711"
replace n3 = "DE712 Frankfurt am Main, Kreisfreie Stadt"                            if NUTS3 == "DE712"
replace n3 = "DE713 Offenbach am Main, Kreisfreie Stadt"                            if NUTS3 == "DE713"
replace n3 = "DE714 Wiesbaden, Kreisfreie Stadt"                                    if NUTS3 == "DE714"
replace n3 = "DE715 Bergstraße"                                                     if NUTS3 == "DE715"
replace n3 = "DE716 Darmstadt-Dieburg"                                              if NUTS3 == "DE716"
replace n3 = "DE717 Groß-Gerau"                                                     if NUTS3 == "DE717"
replace n3 = "DE718 Hochtaunuskreis"                                                if NUTS3 == "DE718"
replace n3 = "DE719 Main-Kinzig-Kreis"                                              if NUTS3 == "DE719"
replace n3 = "DE71A Main-Taunus-Kreis"                                              if NUTS3 == "DE71A"
replace n3 = "DE71B Odenwaldkreis"                                                  if NUTS3 == "DE71B"
replace n3 = "DE71C Offenbach, Landkreis"                                           if NUTS3 == "DE71C"
replace n3 = "DE71D Rheingau-Taunus-Kreis"                                          if NUTS3 == "DE71D"
replace n3 = "DE71E Wetteraukreis"                                                  if NUTS3 == "DE71E"
replace n3 = "DE721 Gießen, Landkreis"                                              if NUTS3 == "DE721"
replace n3 = "DE722 Lahn-Dill-Kreis"                                                if NUTS3 == "DE722"
replace n3 = "DE723 Limburg-Weilburg"                                               if NUTS3 == "DE723"
replace n3 = "DE724 Marburg-Biedenkopf"                                             if NUTS3 == "DE724"
replace n3 = "DE725 Vogelsbergkreis"                                                if NUTS3 == "DE725"
replace n3 = "DE731 Kassel, Kreisfreie Stadt"                                       if NUTS3 == "DE731"
replace n3 = "DE732 Fulda"                                                          if NUTS3 == "DE732"
replace n3 = "DE733 Hersfeld-Rotenburg"                                             if NUTS3 == "DE733"
replace n3 = "DE734 Kassel, Landkreis"                                              if NUTS3 == "DE734"
replace n3 = "DE735 Schwalm-Eder-Kreis"                                             if NUTS3 == "DE735"
replace n3 = "DE736 Waldeck-Frankenberg"                                            if NUTS3 == "DE736"
replace n3 = "DE737 Werra-Meißner-Kreis"                                            if NUTS3 == "DE737"
replace n3 = "DE801 Greifswald, Kreisfreie Stadt"                                      if NUTS3 == "DE801"
replace n3 = "DE803 Rostock, Kreisfreie Stadt"                                      if NUTS3 == "DE803"
replace n3 = "DE804 Schwerin, Kreisfreie Stadt"                                     if NUTS3 == "DE804"
replace n3 = "DE807 Bad Doberan"                                     if NUTS3 == "DE807"
replace n3 = "DE808 Demmin"                                     if NUTS3 == "DE808"
replace n3 = "DE809 Güstrow"                                     if NUTS3 == "DE809"
replace n3 = "DE80A Ludwigslust"                                     if NUTS3 == "DE80A"
replace n3 = "DE80B Mecklenburg-Strelitz"                                     if NUTS3 == "DE80B"
replace n3 = "DE80C Müritz"                                                         if NUTS3 == "DE80C"
replace n3 = "DE80D Nordvorpommern"                                                 if NUTS3 == "DE80D"
replace n3 = "DE80E Nordwestmecklenburg"                                            if NUTS3 == "DE80E"
replace n3 = "DE80F Ostvorpommern"                                            if NUTS3 == "DE80F"
replace n3 = "DE80G Parchim"                                                        if NUTS3 == "DE80G"
replace n3 = "DE80H Rügen"                                                        if NUTS3 == "DE80H"
replace n3 = "DE80I Uecker-Randow"                                                        if NUTS3 == "DE80I"
replace n3 = "DE80J Mecklenburgische Seenplatte"                                    if NUTS3 == "DE80J"
replace n3 = "DE80K Landkreis Rostock"                                    if NUTS3 == "DE80K"
replace n3 = "DE80L Vorpommern-Rügen"                                    if NUTS3 == "DE80L"
replace n3 = "DE80M Nordwestmecklenburg"                                    if NUTS3 == "DE80M"
replace n3 = "DE80N Vorpommern-Greifswald"                                          if NUTS3 == "DE80N"
replace n3 = "DE80O Ludwigslust-Parchim"                                            if NUTS3 == "DE80O"
replace n3 = "DE911 Braunschweig, Kreisfreie Stadt"                                 if NUTS3 == "DE911"
replace n3 = "DE912 Salzgitter, Kreisfreie Stadt"                                   if NUTS3 == "DE912"
replace n3 = "DE913 Wolfsburg, Kreisfreie Stadt"                                    if NUTS3 == "DE913"
replace n3 = "DE914 Gifhorn"                                                        if NUTS3 == "DE914"
replace n3 = "DE915 Göttingen"                                                      if NUTS3 == "DE915"
replace n3 = "DE916 Goslar"                                                         if NUTS3 == "DE916"
replace n3 = "DE917 Helmstedt"                                                      if NUTS3 == "DE917"
replace n3 = "DE918 Northeim"                                                       if NUTS3 == "DE918"
replace n3 = "DE919 Osterode, Harz"                                                 if NUTS3 == "DE919"
replace n3 = "DE91A Peine"                                                          if NUTS3 == "DE91A"
replace n3 = "DE91B Wolfenbüttel"                                                   if NUTS3 == "DE91B"
replace n3 = "DE91C Göttingen"                                                      if NUTS3 == "DE91C"
replace n3 = "DE922 Diepholz"                                                       if NUTS3 == "DE922"
replace n3 = "DE923 Hameln-Pyrmont"                                                 if NUTS3 == "DE923"
replace n3 = "DE925 Hildesheim"                                                     if NUTS3 == "DE925"
replace n3 = "DE926 Holzminden"                                                     if NUTS3 == "DE926"
replace n3 = "DE927 Nienburg Weser)"                                                if NUTS3 == "DE927"
replace n3 = "DE928 Schaumburg"                                                     if NUTS3 == "DE928"
replace n3 = "DE929 Region Hannover"                                                if NUTS3 == "DE929"
replace n3 = "DE931 Celle"                                                          if NUTS3 == "DE931"
replace n3 = "DE932 Cuxhaven"                                                       if NUTS3 == "DE932"
replace n3 = "DE933 Harburg"                                                        if NUTS3 == "DE933"
replace n3 = "DE934 Lüchow-Dannenberg"                                              if NUTS3 == "DE934"
replace n3 = "DE935 Lüneburg, Landkreis"                                            if NUTS3 == "DE935"
replace n3 = "DE936 Osterholz"                                                      if NUTS3 == "DE936"
replace n3 = "DE937 Rotenburg Wümme)"                                               if NUTS3 == "DE937"
replace n3 = "DE938 Heidekreis"                                                     if NUTS3 == "DE938"
replace n3 = "DE939 Stade"                                                          if NUTS3 == "DE939"
replace n3 = "DE93A Uelzen"                                                         if NUTS3 == "DE93A"
replace n3 = "DE93B Verden"                                                         if NUTS3 == "DE93B"
replace n3 = "DE941 Delmenhorst, Kreisfreie Stadt"                                  if NUTS3 == "DE941"
replace n3 = "DE942 Emden, Kreisfreie Stadt"                                        if NUTS3 == "DE942"
replace n3 = "DE943 Oldenburg, Kreisfreie Stadt"                                    if NUTS3 == "DE943"
replace n3 = "DE944 Osnabrück, Kreisfreie Stadt"                                    if NUTS3 == "DE944"
replace n3 = "DE945 Wilhelmshaven, Kreisfreie Stadt"                                if NUTS3 == "DE945"
replace n3 = "DE946 Ammerland"                                                      if NUTS3 == "DE946"
replace n3 = "DE947 Aurich"                                                         if NUTS3 == "DE947"
replace n3 = "DE948 Cloppenburg"                                                    if NUTS3 == "DE948"
replace n3 = "DE949 Emsland"                                                        if NUTS3 == "DE949"
replace n3 = "DE94A Friesland (DE)"                                                 if NUTS3 == "DE94A"
replace n3 = "DE94B Grafschaft Bentheim"                                            if NUTS3 == "DE94B"
replace n3 = "DE94C Leer"                                                           if NUTS3 == "DE94C"
replace n3 = "DE94D Oldenburg, Landkreis"                                           if NUTS3 == "DE94D"
replace n3 = "DE94E Osnabrück, Landkreis"                                           if NUTS3 == "DE94E"
replace n3 = "DE94F Vechta"                                                         if NUTS3 == "DE94F"
replace n3 = "DE94G Wesermarsch"                                                    if NUTS3 == "DE94G"
replace n3 = "DE94H Wittmund"                                                       if NUTS3 == "DE94H"
replace n3 = "DEA11 Düsseldorf, Kreisfreie Stadt"                                   if NUTS3 == "DEA11"
replace n3 = "DEA12 Duisburg, Kreisfreie Stadt"                                     if NUTS3 == "DEA12"
replace n3 = "DEA13 Essen, Kreisfreie Stadt"                                        if NUTS3 == "DEA13"
replace n3 = "DEA14 Krefeld, Kreisfreie Stadt"                                      if NUTS3 == "DEA14"
replace n3 = "DEA15 Mönchengladbach, Kreisfreie Stadt"                              if NUTS3 == "DEA15"
replace n3 = "DEA16 Mülheim an der Ruhr, Kreisfreie Stadt"                          if NUTS3 == "DEA16"
replace n3 = "DEA17 Oberhausen, Kreisfreie Stadt"                                   if NUTS3 == "DEA17"
replace n3 = "DEA18 Remscheid, Kreisfreie Stadt"                                    if NUTS3 == "DEA18"
replace n3 = "DEA19 Solingen, Kreisfreie Stadt"                                     if NUTS3 == "DEA19"
replace n3 = "DEA1A Wuppertal, Kreisfreie Stadt"                                    if NUTS3 == "DEA1A"
replace n3 = "DEA1B Kleve"                                                          if NUTS3 == "DEA1B"
replace n3 = "DEA1C Mettmann"                                                       if NUTS3 == "DEA1C"
replace n3 = "DEA1D Rhein-Kreis Neuss"                                              if NUTS3 == "DEA1D"
replace n3 = "DEA1E Viersen"                                                        if NUTS3 == "DEA1E"
replace n3 = "DEA1F Wesel"                                                          if NUTS3 == "DEA1F"
replace n3 = "DEA22 Bonn, Kreisfreie Stadt"                                         if NUTS3 == "DEA22"
replace n3 = "DEA23 Köln, Kreisfreie Stadt"                                         if NUTS3 == "DEA23"
replace n3 = "DEA24 Leverkusen, Kreisfreie Stadt"                                   if NUTS3 == "DEA24"
replace n3 = "DEA25 Kreis Aachen"                                                   if NUTS3 == "DEA25"
replace n3 = "DEA26 Düren"                                                          if NUTS3 == "DEA26"
replace n3 = "DEA27 Rhein-Erft-Kreis"                                               if NUTS3 == "DEA27"
replace n3 = "DEA28 Euskirchen"                                                     if NUTS3 == "DEA28"
replace n3 = "DEA29 Heinsberg"                                                      if NUTS3 == "DEA29"
replace n3 = "DEA2A Oberbergischer Kreis"                                           if NUTS3 == "DEA2A"
replace n3 = "DEA2B Rheinisch-Bergischer Kreis"                                     if NUTS3 == "DEA2B"
replace n3 = "DEA2C Rhein-Sieg-Kreis"                                               if NUTS3 == "DEA2C"
replace n3 = "DEA2D Städtegregion Aachen"                                           if NUTS3 == "DEA2D"
replace n3 = "DEA31 Bottrop, Kreisfreie Stadt"                                      if NUTS3 == "DEA31"
replace n3 = "DEA32 Gelsenkirchen, Kreisfreie Stadt"                                if NUTS3 == "DEA32"
replace n3 = "DEA33 Münster, Kreisfreie Stadt"                                      if NUTS3 == "DEA33"
replace n3 = "DEA34 Borken"                                                         if NUTS3 == "DEA34"
replace n3 = "DEA35 Coesfeld"                                                       if NUTS3 == "DEA35"
replace n3 = "DEA36 Recklinghausen"                                                 if NUTS3 == "DEA36"
replace n3 = "DEA37 Steinfurt"                                                      if NUTS3 == "DEA37"
replace n3 = "DEA38 Warendorf"                                                      if NUTS3 == "DEA38"
replace n3 = "DEA41 Bielefeld, Kreisfreie Stadt"                                    if NUTS3 == "DEA41"
replace n3 = "DEA42 Gütersloh"                                                      if NUTS3 == "DEA42"
replace n3 = "DEA43 Herford"                                                        if NUTS3 == "DEA43"
replace n3 = "DEA44 Höxter"                                                         if NUTS3 == "DEA44"
replace n3 = "DEA45 Lippe"                                                          if NUTS3 == "DEA45"
replace n3 = "DEA46 Minden-Lübbecke"                                                if NUTS3 == "DEA46"
replace n3 = "DEA47 Paderborn"                                                      if NUTS3 == "DEA47"
replace n3 = "DEA51 Bochum, Kreisfreie Stadt"                                       if NUTS3 == "DEA51"
replace n3 = "DEA52 Dortmund, Kreisfreie Stadt"                                     if NUTS3 == "DEA52"
replace n3 = "DEA53 Hagen, Kreisfreie Stadt"                                        if NUTS3 == "DEA53"
replace n3 = "DEA54 Hamm, Kreisfreie Stadt"                                         if NUTS3 == "DEA54"
replace n3 = "DEA55 Herne, Kreisfreie Stadt"                                        if NUTS3 == "DEA55"
replace n3 = "DEA56 Ennepe-Ruhr-Kreis"                                              if NUTS3 == "DEA56"
replace n3 = "DEA57 Hochsauerlandkreis"                                             if NUTS3 == "DEA57"
replace n3 = "DEA58 Märkischer Kreis"                                               if NUTS3 == "DEA58"
replace n3 = "DEA59 Olpe"                                                           if NUTS3 == "DEA59"
replace n3 = "DEA5A Siegen-Wittgenstein"                                            if NUTS3 == "DEA5A"
replace n3 = "DEA5B Soest"                                                          if NUTS3 == "DEA5B"
replace n3 = "DEA5C Unna"                                                           if NUTS3 == "DEA5C"
replace n3 = "DEB11 Koblenz, Kreisfreie Stadt"                                      if NUTS3 == "DEB11"
replace n3 = "DEB12 Ahrweiler"                                                      if NUTS3 == "DEB12"
replace n3 = "DEB13 Altenkirchen Westerwald)"                                       if NUTS3 == "DEB13"
replace n3 = "DEB14 Bad Kreuznach"                                                  if NUTS3 == "DEB14"
replace n3 = "DEB15 Birkenfeld"                                                     if NUTS3 == "DEB15"
replace n3 = "DEB16 Cochem-Zell"                                                    if NUTS3 == "DEB16"
replace n3 = "DEB17 Mayen-Koblenz"                                                  if NUTS3 == "DEB17"
replace n3 = "DEB18 Neuwied"                                                        if NUTS3 == "DEB18"
replace n3 = "DEB1A Rhein-Lahn-Kreis"                                               if NUTS3 == "DEB1A"
replace n3 = "DEB1B Westerwaldkreis"                                                if NUTS3 == "DEB1B"
replace n3 = "DEB1C Cochem-Zell"                                                    if NUTS3 == "DEB1C"
replace n3 = "DEB1D Rhein-Hunsrück-Kreis"                                           if NUTS3 == "DEB1D"
replace n3 = "DEB19 Rhein-Hunsrück-Kreis"                                           if NUTS3 == "DEB19"
replace n3 = "DEB21 Trier, Kreisfreie Stadt"                                        if NUTS3 == "DEB21"
replace n3 = "DEB22 Bernkastel-Wittlich"                                            if NUTS3 == "DEB22"
replace n3 = "DEB23 Eifelkreis Bitburg-Prüm"                                        if NUTS3 == "DEB23"
replace n3 = "DEB24 Vulkaneifel"                                                    if NUTS3 == "DEB24"
replace n3 = "DEB25 Trier-Saarburg"                                                 if NUTS3 == "DEB25"
replace n3 = "DEB31 Frankenthal Pfalz), Kreisfreie Stadt"                           if NUTS3 == "DEB31"
replace n3 = "DEB32 Kaiserslautern, Kreisfreie Stadt"                               if NUTS3 == "DEB32"
replace n3 = "DEB33 Landau in der Pfalz, Kreisfreie Stadt"                          if NUTS3 == "DEB33"
replace n3 = "DEB34 Ludwigshafen am Rhein, Kreisfreie Stadt"                        if NUTS3 == "DEB34"
replace n3 = "DEB35 Mainz, Kreisfreie Stadt"                                        if NUTS3 == "DEB35"
replace n3 = "DEB36 Neustadt an der Weinstraße, Kreisfreie Stadt"                   if NUTS3 == "DEB36"
replace n3 = "DEB37 Pirmasens, Kreisfreie Stadt"                                    if NUTS3 == "DEB37"
replace n3 = "DEB38 Speyer, Kreisfreie Stadt"                                       if NUTS3 == "DEB38"
replace n3 = "DEB39 Worms, Kreisfreie Stadt"                                        if NUTS3 == "DEB39"
replace n3 = "DEB3A Zweibrücken, Kreisfreie Stadt"                                  if NUTS3 == "DEB3A"
replace n3 = "DEB3B Alzey-Worms"                                                    if NUTS3 == "DEB3B"
replace n3 = "DEB3C Bad Dürkheim"                                                   if NUTS3 == "DEB3C"
replace n3 = "DEB3D Donnersbergkreis"                                               if NUTS3 == "DEB3D"
replace n3 = "DEB3E Germersheim"                                                    if NUTS3 == "DEB3E"
replace n3 = "DEB3F Kaiserslautern, Landkreis"                                      if NUTS3 == "DEB3F"
replace n3 = "DEB3G Kusel"                                                          if NUTS3 == "DEB3G"
replace n3 = "DEB3H Südliche Weinstraße"                                            if NUTS3 == "DEB3H"
replace n3 = "DEB3I Rhein-Pfalz-Kreis"                                              if NUTS3 == "DEB3I"
replace n3 = "DEB3J Mainz-Bingen"                                                   if NUTS3 == "DEB3J"
replace n3 = "DEB3K Südwestpfalz"                                                   if NUTS3 == "DEB3K"
replace n3 = "DEC01 Regionalverband Saarbrücken"                                    if NUTS3 == "DEC01"
replace n3 = "DEC02 Merzig-Wadern"                                                  if NUTS3 == "DEC02"
replace n3 = "DEC03 Neunkirchen"                                                    if NUTS3 == "DEC03"
replace n3 = "DEC04 Saarlouis"                                                      if NUTS3 == "DEC04"
replace n3 = "DEC05 Saarpfalz-Kreis"                                                if NUTS3 == "DEC05"
replace n3 = "DEC06 St. Wendel"                                                     if NUTS3 == "DEC06"
replace n3 = "DED21 Dresden, Kreisfreie Stadt"                                      if NUTS3 == "DED21"
replace n3 = "DED29 Sächsische Schweiz"                                             if NUTS3 == "DED29"
replace n3 = "DED2C Bautzen"                                                        if NUTS3 == "DED2C"
replace n3 = "DED2D Görlitz, Kreisfreie Stadt"                                      if NUTS3 == "DED2D"
replace n3 = "DED2E Meißen"                                                         if NUTS3 == "DED2E"
replace n3 = "DED2F Sächsische Schweiz-Osterzgebirge"                               if NUTS3 == "DED2F"
replace n3 = "DED41 Chemnitz, Kreisfreie Stadt"                                     if NUTS3 == "DED41"
replace n3 = "DED42 Erzgebirgskreis"                                                if NUTS3 == "DED42"
replace n3 = "DED43 Mittelsachsen"                                                  if NUTS3 == "DED43"
replace n3 = "DED44 Vogtlandkreis"                                                  if NUTS3 == "DED44"
replace n3 = "DED45 Zwickau"                                                        if NUTS3 == "DED45"
replace n3 = "DED51 Leipzig, Kreisfreie Stadt"                                      if NUTS3 == "DED51"
replace n3 = "DED52 Leipzig"                                                        if NUTS3 == "DED52"
replace n3 = "DED53 Nordsachsen"                                                    if NUTS3 == "DED53"
replace n3 = "DEE01 Dessau-Roßlau, Kreisfreie Stadt"                                if NUTS3 == "DEE01"
replace n3 = "DEE02 Halle Saale), Kreisfreie Stadt"                                 if NUTS3 == "DEE02"
replace n3 = "DEE03 Magdeburg, Kreisfreie Stadt"                                    if NUTS3 == "DEE03"
replace n3 = "DEE04 Altmarkkreis Salzwedel"                                         if NUTS3 == "DEE04"
replace n3 = "DEE05 Anhalt-Bitterfeld"                                              if NUTS3 == "DEE05"
replace n3 = "DEE06 Jerichower Land"                                                if NUTS3 == "DEE06"
replace n3 = "DEE07 Börde"                                                          if NUTS3 == "DEE07"
replace n3 = "DEE08 Burgenlandkreis"                                                if NUTS3 == "DEE08"
replace n3 = "DEE09 Harz"                                                           if NUTS3 == "DEE09"
replace n3 = "DEE0A Mansfeld-Südharz"                                               if NUTS3 == "DEE0A"
replace n3 = "DEE0B Saalekreis"                                                     if NUTS3 == "DEE0B"
replace n3 = "DEE0C Salzlandkreis"                                                  if NUTS3 == "DEE0C"
replace n3 = "DEE0D Stendal"                                                        if NUTS3 == "DEE0D"
replace n3 = "DEE0E Wittenberg"                                                     if NUTS3 == "DEE0E"
replace n3 = "DEE11 Dessau, Kreisfreie Stadt (until 2005)"   if NUTS3 =="DEE11"
replace n3 = "DEE12 Anhalt-Zerbst (until 2005)"   if NUTS3 =="DEE12"
replace n3 = "DEE13 Bernburg (until 2005)"   if NUTS3 =="DEE13"
replace n3 = "DEE14 Bitterfeld (until 2005)"   if NUTS3 =="DEE14"
replace n3 = "DEE15 Köthen (until 2005)"   if NUTS3 =="DEE15"
replace n3 = "DEE16 Wittenberg (until 2005)"   if NUTS3 =="DEE16"
replace n3 = "DEE33 Bördekreis (until 2005)"   if NUTS3 =="DEE33"
replace n3 = "DEE36 Ohrekreis (until 2005)"   if NUTS3 =="DEE36"
replace n3 = "DEE22 Burgenlandkreis (until 2005)"   if NUTS3 =="DEE22"
replace n3 = "DEE27 Weißenfels (until 2005)"   if NUTS3 =="DEE27"
replace n3 = "DEE23 Mansfelder Land (until 2005)"   if NUTS3 =="DEE23"
replace n3 = "DEE26 Sangerhausen (until 2005)"   if NUTS3 =="DEE26"
replace n3 = "DEE24 Merseburg-Querfurt (until 2005)"   if NUTS3 =="DEE24"
replace n3 = "DEE25 Saalkreis (until 2005)"   if NUTS3 =="DEE25"
replace n3 = "DEE32 Aschersleben-Staßfurt (until 2005)"   if NUTS3 =="DEE32"
replace n3 = "DEE34 Halberstadt (until 2005)"   if NUTS3 =="DEE34"
replace n3 = "DEE35 Jerichower Land (until 2005)"   if NUTS3 =="DEE35"
replace n3 = "DEE38 Quedlinburg (until 2005)"   if NUTS3 =="DEE38"
replace n3 = "DEE39 Schönebeck (until 2005)"   if NUTS3 =="DEE39"
replace n3 = "DEE3A Wernigerode (until 2005)"   if NUTS3 =="DEE3A"
replace n3 = "DEF01 Flensburg, Kreisfreie Stadt"                                    if NUTS3 == "DEF01"
replace n3 = "DEF02 Kiel, Kreisfreie Stadt"                                         if NUTS3 == "DEF02"
replace n3 = "DEF03 Lübeck, Kreisfreie Stadt"                                       if NUTS3 == "DEF03"
replace n3 = "DEF04 Neumünster, Kreisfreie Stadt"                                   if NUTS3 == "DEF04"
replace n3 = "DEF05 Dithmarschen"                                                   if NUTS3 == "DEF05"
replace n3 = "DEF06 Herzogtum Lauenburg"                                            if NUTS3 == "DEF06"
replace n3 = "DEF07 Nordfriesland"                                                  if NUTS3 == "DEF07"
replace n3 = "DEF08 Ostholstein"                                                    if NUTS3 == "DEF08"
replace n3 = "DEF09 Pinneberg"                                                      if NUTS3 == "DEF09"
replace n3 = "DEF0A Plön"                                                           if NUTS3 == "DEF0A"
replace n3 = "DEF0B Rendsburg-Eckernförde"                                          if NUTS3 == "DEF0B"
replace n3 = "DEF0C Schleswig-Flensburg"                                            if NUTS3 == "DEF0C"
replace n3 = "DEF0D Segeberg"                                                       if NUTS3 == "DEF0D"
replace n3 = "DEF0E Steinburg"                                                      if NUTS3 == "DEF0E"
replace n3 = "DEF0F Stormarn"                                                       if NUTS3 == "DEF0F"
replace n3 = "DEG01 Erfurt, Kreisfreie Stadt"                                       if NUTS3 == "DEG01"
replace n3 = "DEG02 Gera, Kreisfreie Stadt"                                         if NUTS3 == "DEG02"
replace n3 = "DEG03 Jena, Kreisfreie Stadt"                                         if NUTS3 == "DEG03"
replace n3 = "DEG04 Suhl, Kreisfreie Stadt"                                         if NUTS3 == "DEG04"
replace n3 = "DEG05 Weimar, Kreisfreie Stadt"                                       if NUTS3 == "DEG05"
replace n3 = "DEG06 Eichsfeld"                                                      if NUTS3 == "DEG06"
replace n3 = "DEG07 Nordhausen"                                                     if NUTS3 == "DEG07"
replace n3 = "DEG09 Unstrut-Hainich-Kreis"                                          if NUTS3 == "DEG09"
replace n3 = "DEG0A Kyffhäuserkreis"                                                if NUTS3 == "DEG0A"
replace n3 = "DEG0B Schmalkalden-Meiningen"                                         if NUTS3 == "DEG0B"
replace n3 = "DEG0C Gotha"                                                          if NUTS3 == "DEG0C"
replace n3 = "DEG0D Sömmerda"                                                       if NUTS3 == "DEG0D"
replace n3 = "DEG0E Hildburghausen"                                                 if NUTS3 == "DEG0E"
replace n3 = "DEG0F Ilm-Kreis"                                                      if NUTS3 == "DEG0F"
replace n3 = "DEG0G Weimarer Land"                                                  if NUTS3 == "DEG0G"
replace n3 = "DEG0H Sonneberg"                                                      if NUTS3 == "DEG0H"
replace n3 = "DEG0I Saalfeld-Rudolstadt"                                            if NUTS3 == "DEG0I"
replace n3 = "DEG0J Saale-Holzland-Kreis"                                           if NUTS3 == "DEG0J"
replace n3 = "DEG0K Saale-Orla-Kreis"                                               if NUTS3 == "DEG0K"
replace n3 = "DEG0L Greiz"                                                          if NUTS3 == "DEG0L"
replace n3 = "DEG0M Altenburger Land"                                               if NUTS3 == "DEG0M"
replace n3 = "DEG0N Eisenach, Kreisfreie Stadt"                                     if NUTS3 == "DEG0N"
replace n3 = "DEG0P Wartburgkreis"                                                  if NUTS3 == "DEG0P"


encode n3, generate(NUTS3fv)  // nuts3 as factor variable labelled with clear names
label save NUTS3fv using "fmt\NUTS3fv", replace  // to be called in asci_Format...do
drop n3




