---
title: |
  | IRT model: AS index for 2013
  | Sustainability indicators with 4 categories 
  | Estimation of restricted model without discrimination parameter
author: "Christoph Wunder"
date: "`r Sys.Date()`"
output:
  html_document:
    fig_caption: yes
    theme: spacelab
    highlight: pygments
    toc: yes
    toc_depth: 4
    number_sections: yes
    toc_float:
      smooth_scroll: no
  pdf_document:
    toc: yes
    toc_depth: '2'
# bibliography: /Users/Christoph/Documents/Uni/Literatur/lit_DB/litdb_sp.bib
# biblio-style: apalike
# link-citations: yes
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(comment=NA, message=FALSE, warning=FALSE)
rm(list=ls())
library(tidyverse)
library(haven)
library(brms)
library(bayesplot)
library(ggplot2)
theme_set(theme_bw())
library(tictoc)
library(sampling)
library(shinystan)
```


# Data

The data are prepared in `/stata/cmd-cs/11-data_processing-cs.do`.

* 2013 cross section data
* We fit a model using all observations with all (9) items. This is the control model.

```{r}
d <- read_dta("../stata/dat/200-asi-ord4-2013master.dta")
d <- rename(d, id = idn)
d$id <- as.integer(d$id)
d$item <- as.factor(d$item)
# d <- d %>% filter( item == c("1", "2", "3") )
table(d$item)
```


```{r}
d$y <- factor( d$y, 
               levels = c("0", "1", "2", "3"), 
               labels = c("very unsustainable", "unsustainable", "sustainable", "very sustainable"),
               ordered = TRUE ) 
glimpse(d, width = 60)
```

Select subsample of data set:

```{r, eval=FALSE}
set.seed(647382)
n <- round(length(unique(d$id))*0.05, 0)
samplecluster <- cluster(d, clustername=c("id"), size=n, method="srswor")
dsample <- getdata(d, samplecluster)
d <- dsample
```

```{r}
d <- d %>% select(id, item, y) %>% relocate(id, item, y)
summary(d)
```

```{r}
ggplot( d, aes(x=y) ) +
  stat_count(width = 0.5) +
  xlab("") +
  facet_wrap(~item)
```

# Fitting the model in brms

```{r, message=TRUE, warning=TRUE}
tic("fit1")
prior <-
  # unit-specific effects 
  prior("normal(0, 3)", class = "sd", group = "id") +
  # item-specific effects 
  prior("normal(0, 3)", class = "sd", group = "item")
formula <- brmsformula(
  y ~ 1 +  (1|i|item) + (1|id)
)
fit.r <- brm( 
  formula = formula,
  data = d,
  family = cumulative(link = "logit"),
  prior = prior,
  cores = 4,
  iter = 1000,
  warmup = 500,
  refresh = 0,
  file = "../results/103-cs-2013-wo-disc.rds"
)
toc()
```

```{r}
summary(fit.r)
```

Extract diagnostic quantities:

```{r}
# help("diagnostic-quantities")

# extract the number of divergence transitions
np <- nuts_params(fit.r)
sum(subset(np, Parameter == "divergent__")$Value)
```


```{r}
prior_summary(fit.r)
```

# Model comparison

Load results from model with discrimination parameter

```{r}
fit.ur <- readRDS("../results/90-cs-2013.rds")
```

```{r}
# model comparison using LOO-CV
loo_ur <- loo(fit.ur) # unrestricted model with discrimination parameter
loo_r  <- loo(fit.r) # restricted model without discrimination parameter
loo_compare <- loo_compare(loo_ur, loo_r)
print(loo_compare, simplify = FALSE)
```


# Original computing environment {-}

```{r}
devtools::session_info()
```


```{r}
knitr::knit_exit()
```

